In [1]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Importing dataset
df = pd.read_csv("data.csv", sep=' ')
df

Employee   Age   Salary Purchased
0   Anjali  45.0  71000.0        No
1    Parul  28.0  48000.0       Yes
2  Kanisha  31.0  53000.0        No
3    Parul  35.0  61000.0        No
4  Kanisha  42.0      NaN       Yes
5   Anjali  35.0  59000.0       Yes
6    Parul   NaN  53000.0        No
7   Anjali  47.0  80000.0       Yes
8  Kanisha  51.0  81000.0        No
9   Anjali  36.0  68000.0       Yes

In [3]:
X = df.iloc[:,[0,1,2]].values
y = df.iloc[:,3].values

In [4]:
X

array([['Anjali', 45.0, 71000.0],
       ['Parul', 28.0, 48000.0],
       ['Kanisha', 31.0, 53000.0],
       ['Parul', 35.0, 61000.0],
       ['Kanisha', 42.0, nan],
       ['Anjali', 35.0, 59000.0],
       ['Parul', nan, 53000.0],
       ['Anjali', 47.0, 80000.0],
       ['Kanisha', 51.0, 81000.0],
       ['Anjali', 36.0, 68000.0]], dtype=object)

In [5]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [6]:
#Handling missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
X

array([['Anjali', 45.0, 71000.0],
       ['Parul', 28.0, 48000.0],
       ['Kanisha', 31.0, 53000.0],
       ['Parul', 35.0, 61000.0],
       ['Kanisha', 42.0, 63777.77777777778],
       ['Anjali', 35.0, 59000.0],
       ['Parul', 38.888888888888886, 53000.0],
       ['Anjali', 47.0, 80000.0],
       ['Kanisha', 51.0, 81000.0],
       ['Anjali', 36.0, 68000.0]], dtype=object)

In [7]:
#encoding the independent variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('endoer', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)
X = np.array(X)
X

array([[1.0, 0.0, 0.0, 45.0, 71000.0],
       [0.0, 0.0, 1.0, 28.0, 48000.0],
       [0.0, 1.0, 0.0, 31.0, 53000.0],
       [0.0, 0.0, 1.0, 35.0, 61000.0],
       [0.0, 1.0, 0.0, 42.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 59000.0],
       [0.0, 0.0, 1.0, 38.888888888888886, 53000.0],
       [1.0, 0.0, 0.0, 47.0, 80000.0],
       [0.0, 1.0, 0.0, 51.0, 81000.0],
       [1.0, 0.0, 0.0, 36.0, 68000.0]], dtype=object)

In [8]:
#encoding the dependent variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [9]:
#split data into train and test dataset
from sklearn.model_selection import train_test_split  #(for python2)
#from sklearn.model_selection import train_test_split  (for python3)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)
print('X_train.shape: ', X_train.shape)
print('X_test.shape:  ', X_test.shape)
print('y_train.shape: ', y_train.shape)
print('y_test.shape:  ', y_test.shape)

X_train.shape:  (8, 5)
X_test.shape:   (2, 5)
y_train.shape:  (8,)
y_test.shape:   (2,)


In [10]:
#feature scaling of training dataset
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [11]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.62900131,  0.08470159],
       [ 1.        , -0.37796447, -0.77459667, -0.40813062,  0.52865477],
       [-1.        , -0.37796447,  1.29099445, -1.7909732 , -1.57428135],
       [-1.        , -0.37796447,  1.29099445,  0.0912292 , -1.04854732],
       [ 1.        , -0.37796447, -0.77459667,  1.49327793,  1.79041645],
       [-1.        , -0.37796447,  1.29099445, -0.58098595, -0.20737287],
       [ 1.        , -0.37796447, -0.77459667,  1.14756728,  0.84409519],
       [ 1.        , -0.37796447, -0.77459667, -0.58098595, -0.41766648]])

In [12]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.27240724, -1.04854732],
       [-1.        ,  2.64575131, -0.77459667,  2.18469922,  1.89556325]])